{
 "title": "Bookstore - DevOps Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "bookstore_up" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bookstore_requests_total" }
   ]
  },
  {
   "title": "Orders Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bookstore_orders_created_total" }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bookstore_errors_5xx_total" }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(bookstore_requests_total[1m])",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Business Metrics (Books & Orders)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bookstore_books_added_total", "legendFormat": "books added" },
    { "expr": "bookstore_orders_created_total", "legendFormat": "orders created" }
   ]
  },
  {
   "title": "Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "bookstore_request_latency_ms", "legendFormat": "latency" }
   ]
  },
  {
   "title": "Running Build",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "bookstore_build_info" }
   ]
  }
 ]
}